# Modo de depuração para correção de problemas no plugin.
debug-mode: false

#      ___      _        _
#     /   \__ _| |_ __ _| |__   __ _ ___  ___
#    / /\ / _` | __/ _` | '_ \ / _` / __|/ _ \
#   / /_// (_| | || (_| | |_) | (_| \__ \  __/
#  /___,' \__,_|\__\__,_|_.__/ \__,_|___/\___|
#
# Configurações do banco de dados.

database:
   # Determina o tipo de banco de dados. Valores válidos: [SQLITE, MYSQL, HIKARI (recomendado)]
   storage-type: SQLITE

   # Dados para conexão ao banco de dados MYSQL.
   data:
      # Endereço de conexão do banco de dados. [EX: 127.0.0.1]
      host: localhost
      # Porta de conexão do banco de dados. [EX: 3306]
      port: 3306
      # Nome do banco de dados a ser conectado. [EX: minecraft]
      database: ''
      # Usuário de conexão. [EX: root]
      username: ''
      # Senha do usuário de conexão: [EX: 123]
      password: ''

Comando:
   Comando: 'crate'
   Aliases: [crates, caixa, caixas]

# Carregar as crates depois de x tempo que o server ligar
Carregar depois: 20 # Em ticks (20 ticks = 1 segundo)

# Ativar o sistema de filtro
Filtro: true

# Ativar o menu de preview
Preview: true

# Usar as partículas do Packet-Events
# Caso false, usará as do ProtocolLIB
packet-events-particles: false

# Limite máximo de abertura de keys por click
all-limit: 100

# Sistema de lores
lore:
   filter-remove: ['&cClique para remover do filtro']

# Sistema de limpar as possíveis caixas "bugadas"
crate-cleaner:
   enable: false
   # em segundos
   time: 300

Mensagens:
   Segurando: '&cVocê deve estar segurando uma key para abrir a crate &7{crate}&c.'
   Key nao: '&cEsta key não abre a crate &7{crate}&c.'
   Ja abrindo: '&cAlguém já está abrindo a crate &7{crate}&c neste local.'
   Mal configurada: '&cEsta crate não existe ou está mal configurada.'
   Setada: '&aCrate &7{crate} &asetada.'
   Removida: '&aCrate &7{crate} &aremovida.'
   Inv cheio: '&cSeu inventário está cheio.'
   Permissao: '&cVocê não tem permissão para isso.'
   Nao encontrado: '&cJogador não encontrado.'
   Nao e numero: '&cO argumento não é um número.'
   Deu crate: '&aVocê deu &7{quantia}x {crate} &apara o jogador &7{player}&a.'
   Recebeu crate: '&aVocê recebeu &7{quantia}x {crate}&a.'
   Deu key: '&aVocê deu &7{quantia}x &akey(s) da crate &7{crate} &apara o jogador &7{player}&a.'
   Recebeu key: '&aVocê recebeu &7{quantia}x &a key(s) da crate &7{crate}&a.'
   Deu todos: '&aVocê deu &7{quantia}x &akey(s) da crate &7{crate}&a para &7({players}) &ajogadores online.'
   AdicionadoFiltro: '&aEste item foi adicionado ao filtro.'
   RemovidoFiltro: '&aEste item foi removido do filtro.'
   Descompactar-Segurando: '&cVocê precisa estar segurando keys compactadas.'
   Descompactar-Encontrado: '&cA crate vinculada nesta key não foi encontrada.'
   Descompactar-Minimo: '&cA sua key já está no mínimo possível.'
   Descompactar: '&a{amount} Keys descompactadas.'
   Recebeu todos:
      - ''
      - '&aTodos os jogadores receberam &7{quantia}x &akey(s) da crate &7{crate}&a.'
      - ''
   Help:
      - '&c&lERRO! &cComandos disponíveis:'
      - '&c-> /crate givecrate'
      - '&c-> /crate givekey'
      - '&c-> /crate keyall'
      - '&c-> /crate reload'
      - ''
#
#
Sons:
   Erro:
      Ativar: true
      Som: 'CAT_MEOW'
   Ganhou:
      Ativar: true
      Som: 'ORB_PICKUP'
#
#
##
# Lista de efeitos da 1.8: https://helpch.at/docs/1.8.8/org/bukkit/Effect.html
# Lista de efeitos da 1.16: https://helpch.at/docs/1.16.1/org/bukkit/Effect.html
#
# Lista de sons da 1.8: https://helpch.at/docs/1.8.8/org/bukkit/Sound.html
# Lista de sons da 1.16: https://helpch.at/docs/1.16.1/org/bukkit/Sound.html
#
Explode:
   Som: 'EXPLODE'
   Efeitos:
   - 'LAVADRIP:40' # Efeito:intensidade
   - 'VILLAGER_THUNDERCLOUD:300' # Efeito:intensidade
   - 'CLOUD:230' # Efeito:intensidade
   - 'EXPLOSION_HUGE:20' # Efeito:intensidade
#
#
Setas:
   Voltar:
      CustomSkull: false
      URL: ''
      ID: ARROW
      Data: 0
      Glow: true
      Name: '&cVoltar'
      Lore:
      - '&7Clique para voltar ao menu anterior.'
   Anterior:
      CustomSkull: false
      URL: ''
      ID: ARROW
      Data: 0
      Glow: true
      Name: '&cVoltar'
      Lore:
      - '&7Clique para voltar à página anterior.'
   Proximo:
      CustomSkull: false
      URL: ''
      ID: ARROW
      Data: 0
      Glow: true
      Name: '&aPróxima'
      Lore:
      - '&7Clique para ir à próxima página.'