# Modo de depuração para correção de problemas no plugin.
debug-mode: false

#      ___      _        _
#     /   \__ _| |_ __ _| |__   __ _ ___  ___
#    / /\ / _` | __/ _` | '_ \ / _` / __|/ _ \
#   / /_// (_| | || (_| | |_) | (_| \__ \  __/
#  /___,' \__,_|\__\__,_|_.__/ \__,_|___/\___|
#
# Configurações do banco de dados.

database:
   # Determina o tipo de banco de dados. Valores válidos: [SQLITE, MYSQL, HIKARI (recomendado)]
   storage-type: SQLITE

   # Dados para conexão ao banco de dados MYSQL.
   data:
      # Endereço de conexão do banco de dados. [EX: 127.0.0.1]
      host: localhost
      # Porta de conexão do banco de dados. [EX: 3306]
      port: 3306
      # Nome do banco de dados a ser conectado. [EX: minecraft]
      database: ''
      # Usuário de conexão. [EX: root]
      username: ''
      # Senha do usuário de conexão: [EX: 123]
      password: ''

# Este limite serve para recolher recompensas
# Desativar ou aumentar o limite pode gerar lag
# e em alguns casos crashar o servidor.
limit:
   enabled: true
   # Máximo que irá recolher por vez
   max: 1000

# Mundos que não poderão coletar recompensas
world-reward-collect-blacklist: [ 'none' ]

# Carregar as crates depois de x tempo que o server ligar
Carregar depois: 20 # Em ticks (20 ticks = 1 segundo)

# Ativar o sistema de filtro
Filtro: true

# Ativar o menu de preview
Preview: true

# Ativar o menu ao digitar /crate
crate-menu: false

# Usar as partículas do Packet-Events
# Caso false, usará as do ProtocolLIB
packet-events-particles: false

# Dar as keys compactadas em 1 item só
give-compact: true

# Limite máximo de abertura de keys por click
all-limit: 100

# Sistema de lores
lore:
   filter-remove: ['&cClique para remover do filtro']

# Sistema de limpar as possíveis caixas "bugadas"
crate-cleaner:
   enable: false
   # em segundos
   time: 300

# Sistema de sons
Sons:
   Erro:
      Ativar: true
      Som: 'CAT_MEOW'
   Ganhou:
      Ativar: true
      Som: 'ORB_PICKUP'

# Lista de efeitos da 1.8: https://helpch.at/docs/1.8.8/org/bukkit/Effect.html
# Lista de efeitos da 1.16: https://helpch.at/docs/1.16.1/org/bukkit/Effect.html
# Lista de sons da 1.8: https://helpch.at/docs/1.8.8/org/bukkit/Sound.html
# Lista de sons da 1.16: https://helpch.at/docs/1.16.1/org/bukkit/Sound.html
Explode:
   Som: 'EXPLODE'
   Efeitos:
   - 'LAVADRIP:40' # Efeito:intensidade
   - 'VILLAGER_THUNDERCLOUD:300' # Efeito:intensidade
   - 'CLOUD:230' # Efeito:intensidade
   - 'EXPLOSION_HUGE:20' # Efeito:intensidade